<?php

/**
 * @file
 * Defines all the hooks this module implements.
 *
 * upitt_islandora_inventory_audit.module: defines paths (drupal menu items) as entry points.
 *
 */

// Permissions.
define('UPITT_ISLANDORA_INVENTORY_AUDIT', 'inventory audit');

/**
 * Implements hook_menu().
 */
function upitt_islandora_inventory_audit_menu() {
  return array(
    'admin/islandora/inventory_audit' => array(
      'title' => 'Islandora Inventory Audit',
      'description' => 'Settings for the Islandora Inventory Audit module.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('upitt_islandora_inventory_audit_admin_form'),
      'access arguments' => array(UPITT_ISLANDORA_INVENTORY_AUDIT),
      'file' => 'includes/admin.form.inc',
    ),
    // reports selection page
    'admin/islandora/inventory_audit/reports' => array(
      'title' => 'Inventory Audit Reports',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('upitt_islandora_inventory_audit_reports_form'),
      'type' => MENU_LOCAL_TASK,
      'file' => 'includes/reports.form.inc',
      'access arguments' => array(UPITT_ISLANDORA_INVENTORY_AUDIT),
    ),
    // report handler
    'admin/islandora/inventory_audit/reports/%/%' => array(
      'title' => 'Inventory Audit Reports',
      'page callback' => 'upitt_islandora_inventory_audit_reports_report',
      'page arguments' => array(4,5),
      'type' => MENU_LOCAL_TASK,
      'file' => 'includes/reports.form.inc',
      'access arguments' => array(UPITT_ISLANDORA_INVENTORY_AUDIT),
    ),
    'islandora/object/%islandora_object/manage/audit_upitt_workflow/inventory_audit' => array(
      'title' => 'Inventory Audit',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('upitt_islandora_inventory_audit_form', 2),
      'type' => MENU_LOCAL_TASK,
      'file' => 'includes/islandora_object_audit.form.inc',
      'access arguments' => array(UPITT_ISLANDORA_INVENTORY_AUDIT),
    ),
  );
}

/**
 * Implements hook_permission().
 */
function upitt_islandora_inventory_audit_permission() {
  return array(
    UPITT_ISLANDORA_INVENTORY_AUDIT => array(
      'title' => t('Use the Inventory Audit module'),
      'description' => t('User can use the Inventory Audit module.'),
    ),
  );
}

/**
 * Implements hook_preprocess_theme().
 *
 * This code will remove the sidebar and add CSS if this is the right page.
 */
function upitt_islandora_inventory_audit_preprocess_page(&$vars) {
  $item = menu_get_item();
  $path = drupal_get_path('module', 'upitt_islandora_inventory_audit');
  if (is_array($item)) {
    if (($item['path'] == 'islandora/object/%/manage/audit_upitt_workflow/inventory_audit') ||
        (strstr($item['path'], 'admin/islandora/inventory_audit/reports/')) ) {
      drupal_add_css($path . '/css/audit_details.css');
      $vars['page']['sidebar'] = array();
    }
  }
}

/**
 * Implement hook theme
 */
function upitt_islandora_inventory_audit_theme() {
  return array(
    'upitt_islandora_inventory_audit_report' => array(
      'variables' => array('table' => NULL, 'count_rows' => '', 'links' => '', 'pager' => '', 'table_markup' => ''),
      'template' => 'theme/upitt-islandora-inventory-audit-report',
    ),
  );
}